Adding new module stock_warehouse_interwarehouse
open-synergy/opnsynid-stock-logistics-warehouse pull request #12
Opened 2017-01-15 08:10 UTC by mikevhe18

2017-01-15 10:26 UTC, andhit-r requested changes

2017-01-15 10:26 UTC, andhit-r commented on stock_warehouse_interwarehouse/models/stock_warehouse.py
> +    )
Tambahin 2 fields:

1. inter_warehouse_pull_route_id
2. inter_warehouse_push_route_id

2017-01-15 10:26 UTC, andhit-r commented on stock_warehouse_interwarehouse/views/stock_warehouse_view.xml
> +                </xpath>
Jangan lupa menambahkan 2 field baru

2017-01-16 04:25 UTC, andhit-r requested changes
@mikevhe18 nama modulnya diganti jadi stock_interwarehouse_operation.

Jngan lupa pakai git mv

2017-01-17 12:48 UTC, andhit-r requested changes

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def get_parent_location(self):
Hasil dari fungsi ini bisa didapatkan melalui field view_location_id stock.warehouse hehehehe

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def get_stock_location(self):
Klo ini melalui lot_stock_id

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def create_location_pull(self, company_id):
Mike biasakan menggunakan awalan _ jika method sifatnya private. Btw kenapa harus ada param company_id? stock.warehouse punya field company_id. Pakai itu aja

Kemudian  pakai @api.multi jangan @api.model

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def create_location_push(self, company_id):
Pakai awalan _ juga. Gunakan company_id dari stock.arehouse

Pakai api.multi

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def create_type_interwarehouse_in(self):
Pakai awalan _ . Pakai @api.multi

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    @api.model
api.multi

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def create_route_interwarehouse_push(self):
Gunakan api.multi. Gunakan _

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def create_route_interwarehouse_pull(self):
Pakai api.multi. Gunakan _

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def button_auto_create(self):
pakai self.ensure_one()

2017-01-17 12:48 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def button_reset(self):
Tidak perlu ada button reset. Penghapusan sebaikanya dilakukan secara manual

2017-01-18 03:10 UTC, andhit-r requested changes

2017-01-18 03:10 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def _create_location_pull(self):
Mike ini ksh self.ensure_one juga

2017-01-18 03:10 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def _create_location_push(self):
Tambahin self.ensure_one

2017-01-18 03:10 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def _create_type_interwarehouse_in(self):
self.ensure_one

2017-01-18 03:10 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def _create_type_interwarehouse_out(self):
self.ensure_one

2017-01-18 03:10 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def _create_route_interwarehouse_push(self):
self.ensure_one

2017-01-18 03:10 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def _create_route_interwarehouse_pull(self):
self.ensure_one

2017-01-19 22:28 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def button_auto_create(self):
@mikevhe18 ada alasan kenapa lo satuin untuk buttonnya?

2017-01-19 23:25 UTC, andhit-r requested changes

2017-01-19 23:25 UTC, andhit-r commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +                        'picking_type_id': self.interwarehouse_out_type_id.id
@mikevhe18 ini kurang location_src_id. Harusnya diisi dengan lokasi stock warehouse yg terkait

2017-01-20 02:23 UTC, mikevhe18 commented on stock_interwarehouse_operation/models/stock_warehouse.py
> +    def button_auto_create(self):
@andhit-r biar ga terlalu banyak fungsi aja mas

2017-01-20 03:27 UTC, andhit-r approved these changes

2017-01-20 03:28 UTC, merged